version: "2.4"

services:
    selenoid:
        image: aerokube/selenoid:1.10.0
        networks:
            - my-network
        volumes:
            - ~/Documents/Project/tmp/:/etc/selenoid/
            - /var/run/docker.sock:/var/run/docker.sock
        command: ["-conf", "/etc/selenoid/browsers.json", "-container-network", "my-network"]
        ports:
            - "4444:4444"

    db:
        image: percona:latest
        container_name: mysql
        restart: always

        ports:
            - "3306:3306"
        volumes:
            - ~/Documents/Project/tmp/:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: root
        networks:
            - my-network


    vk_api:
        image: vk_api:latest
        build: .
        ports:
            - "1052:1052"
        networks:
            - my-network

    myapp:
        image: myapp:latest
        container_name: myapp
        ports:
            - "5555:5555"
        depends_on:
             - db
        volumes:
            - ~/Documents/Project/tmp/:/conf_dir
        entrypoint: "/app/myapp --config=/conf_dir/conf"
        links:
            - db
            - vk_api
        restart: always
        networks:
            - my-network

networks:
    my-network:
        external:
            name: my-network