version: "2.4"

services:
    selenoid:
        image: aerokube/selenoid:1.10.0
        container_name: selenoid
        networks:
            - my-network
        volumes:
            - $PWD/config/:/etc/selenoid/:ro
            - /var/run/docker.sock:/var/run/docker.sock
        command: ["-container-network", "my-network", "-service-startup-timeout" , "240s", "-session-delete-timeout", "90s" , "-timeout" , "240s"]
        ports:
            - "4444:4444"

    db:
        image: percona:latest
        container_name: mysql
        restart: always

        ports:
            - "3306:3306"
        volumes:
            - $PWD/tmp/:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: root
        healthcheck:
            test: [ "CMD", "mysqladmin", "-uroot", "-proot", "ping", "-h", "127.0.0.1" ]
            timeout: 30s
            retries: 10
        networks:
            - my-network

    vk_api:
        image: vk_api:latest
        container_name: vk
        build: .
        ports:
            - "1052:1052"
        networks:
            - my-network

    myapp:
        image: myapp:latest
        container_name: myapp
        ports:
            - "5555:5555"
        depends_on:
            db:
                condition: service_healthy
        volumes:
            - $PWD/tmp/:/conf_dir
        entrypoint: "/app/myapp --config=/conf_dir/conf"
        links:
            - db
            - vk_api
        restart: always
        networks:
            - my-network


networks:
    my-network:
        external:
            name: my-network